name: desafio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.6996
  intl:
  equatable: ^2.0.3
  #bloc
  flutter_bloc: ^8.0.1
  #get_it
  get_it: ^7.2.0
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  provider:
  path_provider: ^2.0.11
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  flutter_svg:
  cloud_firestore: ^3.2.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  bloc: ^8.0.3
  email_validator: '^2.1.16'
  either_dart: ^0.2.0
  stream_transform: ^2.0.0
  flutter_statusbarcolor_ns: ^0.4.0
  bloc_concurrency:
  http:
  http_interceptor:
  google_fonts:
  #icon google
  font_awesome_flutter: ^9.0.0
  flutter_launcher_icons: ^0.10.0
  google_sign_in: ^5.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/splashpage/splash.png" 


flutter_native_splash:
  color: "#00C1AF" 
  image: "assets/img/splashpage/splash.png"
  android: true
  ios: true
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:
  assets:
    - assets/img/splashpage/splash.png
    - assets/img/splashpage/logo.png
    - assets/img/splashpage/reslogo.png
    - assets/img/onboarding/cell.png
    - assets/img/onboarding/moca.png
    - assets/img/onboarding/cellmoca.png

  uses-material-design: true
  

fonts:
    - family: Khalid
      fonts:
        - asset: assets/fonts/ae_Khalid.ttf


